---
openapi: 3.0.0
info:
  title: Challenge 5
  description: Dokumentasi API Challenge 5
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/tantrifadh/Challenge5/1.0.0
  description: SwaggerHub API Auto Mocking
paths: {}
components: {}
